### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by arya020** [jinwoo-Bae/spring-react-google-oauth2#3]
![Screenshot (253)](https://github.com/CNJingo/spring-react-google-oauth2/assets/79752258/53852169-2b3f-4560-a184-e3d4a1c1be5d)

**Comment by 5N3H4515H** [comment]
@arya020 In google console under "Authorized redirect URIs"
 we have to add these 2 URLs "http://localhost:8080/v1/oauth/user/info", "http://localhost:8080/v1/oauth/login" right?

**Comment by arya020** [comment]
@5N3H4515H did that.. still not working...

**Comment by baezzys** [comment]
@arya020 Hi, Can I reproduce this issue? If you provide a sample file for reproducing issue, I'll check it.

**Comment by baezzys** [comment]
Please check #2 . Thanks.
